### ISSUE TITLE
Token Unknown

### ISSUE THREAD

**Issue by tomgco** [steinwedel/ioBroker.mihome-air#1]
Hello, 

I am wondering where the token is taken from or how do I retrieve it?

**Comment by steinwedel** [comment]
Hello, 
I changed the adapter, so it is retrieving the token by it's own. Please inform me, if this works for you.

**Comment by tomgco** [comment]
@steinwedel So it doesn't seem to work for me, but I might not running this at the right point, do I have to do this before it is connected to my home network, or while it is still in the setup stage (when it is running its own WiFi connection)

**Comment by tomgco** [comment]
I have just read https://github.com/OpenMiHome/mihome-binary-protocol/blob/master/doc/PROTOCOL.md and it explains that only non-initialised devices now expose their tokens.
